hw_6 add files task_1.py task_2.py
eugene-okulik/Maksim pull request #10
Opened 2023-12-12 20:45 UTC by MaximStQA

2023-12-12 20:46 UTC, MaximStQA commented
Женя Привет! проверь пожалуйста pr

2023-12-13 07:24 UTC, eugene-okulik requested changes

2023-12-13 07:24 UTC, eugene-okulik commented on homework/maksim_stulau/homework_6/task_1.py
> +print(out_text)
Сейчас распечатывается список, а нужно, чтобы распечатывался текст в преобразованном виде

2023-12-13 07:24 UTC, eugene-okulik commented on homework/maksim_stulau/homework_6/task_1.py
> +        Integer urna nisl, facilitates vitae semper at, dignissim vitae libero"
Согласно PEP-8, длинные строки текста разделяются вот так:
```python
text = (
    "Etiam incident neque erat, quis molestie enim imperdiet vel. "
    + "Integer urna nisl, facilitates vitae semper at, dignissim vitae libero"
)
```

2023-12-13 07:24 UTC, eugene-okulik commented on homework/maksim_stulau/homework_6/task_2.py
> +        print(i)
Сейчас вместо числа 15 распечатывается не только FuzzBuzz, но и Fuzz, так как 15 делится и на 3 и на 5, вместо него должно распечатываться только FuzzBuzz

2023-12-13 08:15 UTC, cryptomup commented on homework/maksim_stulau/homework_6/task_2.py
> +        print(i)
ок, вечером переделаю

2023-12-13 08:16 UTC, cryptomup commented on homework/maksim_stulau/homework_6/task_1.py
> +        Integer urna nisl, facilitates vitae semper at, dignissim vitae libero"
ок, Спасибо!

2023-12-13 08:18 UTC, cryptomup commented on homework/maksim_stulau/homework_6/task_1.py
> +print(out_text)
чтобы распечаталась строка вчера так и не выстрадал, наведи пожалуйста на мысль как это сделать

2023-12-14 22:23 UTC, MaximStQA commented
Женя добрый пол вторго ночи,) я добавил pr с исправлениями, будет время проверь пожалуйста.

2023-12-16 06:58 UTC, eugene-okulik approved these changes

2023-12-16 06:58 UTC, eugene-okulik commented on homework/maksim_stulau/homework_6/task_2.py
> +        print(i)
Ну, тоже сойдет, но можно было сделать без вложенных условий:
```python
for i in range(1, 100):
    if i % 5 == 0 and i % 3 == 0:
        print('FuzzBuzz')
    elif i % 3 == 0:
        print('Fuzz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)
```

2023-12-16 06:59 UTC, merged