hw11_t_1.py added
eugene-okulik/Maksim pull request #21
Opened 2024-01-13 17:37 UTC by MaximStQA

2024-01-13 17:38 UTC, MaximStQA commented
Женя Привет! проверь пожалуйста мой pr

2024-01-14 11:59 UTC, eugene-okulik requested changes
Самое выбивающееся - это то, что все книги - для одного класса (причем, даже не просто для седьмого, а для седьмого Б). И кстати у тебя, по сути, то же самое хранится потом и в индивидуальных характеристиках в переменной `class_name`. Похоже, ты где-то забыл убрать или у тебя была какая-то в этом цель ))))

2024-01-14 11:59 UTC, eugene-okulik commented on homework/maksim_stulau/homework_11/hw11_t_1.py
> +    school_class = "7b"
В этом блоке перечисляются свойства, которые будут одинаковыми у всех объектов этого класса.  
Получается, что все учебники в школьной библиотеке будут для класса 7b, а все остальные классы - без учебников, даже классу 7a учебников нет.

2024-01-14 12:03 UTC, eugene-okulik commented on homework/maksim_stulau/homework_11/hw11_t_1.py
> +    def get_textbook(self):
Писал еще здесь коммент, но он потерялся. Напишу еще раз  
Этот метод делает то же самое, что делает метод `get_book` родительского класса, но реализован с учетом особенностей этого текущего дочернего класса. В такой ситуации нужно назвать этот метод так же как в родительском классе.  
Разная реализация одного и того же метода в подклассах называется полиморфизмом. В следующем занятии ты с ним познакомишься.

2024-01-15 08:23 UTC, eugene-okulik approved these changes

2024-01-15 08:23 UTC, merged