homework_4
eugene-okulik/Maksim pull request #6
Opened 2023-12-04 22:01 UTC by MaximStQA

сломал голову доставая последний элемент значения ключа, а дальше уже по шаблону)

2023-12-05 07:35 UTC, eugene-okulik requested changes

2023-12-05 07:35 UTC, eugene-okulik commented on homework/maksim_stulau/homework_4/task_1.py
> +# print(last_value[-1])
А чего закомментировал в итоге эту строку?

2023-12-05 07:35 UTC, eugene-okulik commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict["i am a tuple"] = 1
В задании было 

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнил как будто там

> добавьте элемент с ключом 'i am a tuple' и любым значением

2023-12-05 08:30 UTC, cryptomup commented on homework/maksim_stulau/homework_4/task_1.py
> +# print(last_value[-1])
да, десятая строка должна быть раскоменчена
оперался на требование : вывести итоговый дикт dict
а первое задание интерпритировал как промежуточное
# например убедился что искомое значение есть и значит могу проходить по флоу дальше

2023-12-05 08:33 UTC, cryptomup commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict["i am a tuple"] = 1
понял, вечером переделаю

2023-12-05 20:51 UTC, MaximStQA commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict["i am a tuple"] = 1
Женя, внес исправления в 10 и 20 строках, проверь пожалуйста

2023-12-05 20:57 UTC, MaximStQA commented
Женя, внес исправления в 10 и 20 строках, проверь пожалуйста

2023-12-06 20:22 UTC, eugene-okulik requested changes

2023-12-06 20:22 UTC, eugene-okulik commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict["('i am a tuple',)"] = 1
Не, не угадал )))  
Нужно, чтобы ключом был кортеж с одним значением, а у тебя сейчас строка.

2023-12-07 11:52 UTC, eugene-okulik commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict["('i am a tuple',)"] = 1
ага. А точнее, элемент словаря, у которого ключ - кортеж.

2023-12-07 19:46 UTC, MaximStQA commented
Женя Привет! проверь пожалуйста

2023-12-08 15:39 UTC, eugene-okulik commented on homework/maksim_stulau/homework_4/task_1.py
> +new_dict[(('i am a tuple',))] = 'try is 100500'
Чота много скобок, достаточно было одной парочки

2023-12-08 15:44 UTC, merged