added files:  file_hw_1.py, file_hw_2.py, file_hw_3.py
eugene-okulik/Maksim pull request #8
Opened 2023-12-09 19:01 UTC by MaximStQA

2023-12-09 19:12 UTC, MaximStQA commented
не понимаю почему проверка падает

2023-12-09 21:36 UTC, MaximStQA commented
таки прошёл

2023-12-10 19:35 UTC, MaximStQA commented
тут ещё чудным образом выяснил что второй вариант решения в задании 2 можно написать на три строки короче
![Снимок экрана от 2023-12-10 20-30-07](https://github.com/eugene-okulik/Maksim/assets/136249540/4c86fbdf-65a3-457f-bfc2-5edcf5eb14f9)
убрать строки 41, 42, 43 а 37, 38, 39 написать так:
num1 = int(result[value_1:23]) + 10
num2 = int(result[value_2:51]) + 10
num3 = int(result[value_3:84]) + 10
и конечный индекс после двоеточия можно тоже не писать

2023-12-11 09:50 UTC, eugene-okulik requested changes

2023-12-11 09:50 UTC, eugene-okulik commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +ind_num_1 = result_1.index("42")
Если мы знаем еще в момент написания программы какое там будет число, то зачем на программа? Мы можем просто сделать 42 + 10  
Нужно, чтобы программа сама находила число в этой строке и делала с ним необходимое действие.  
Фишка в том, чтобы найти что-то одинаковое во всех строках, и, опираясь на это, получать из строки число.

2023-12-11 09:50 UTC, eugene-okulik commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +num_1 = result_1[20:22]
И даже если пользоваться твоим подходом, то сейчас, получается, ты вычислил программно место, где находится число 42, а потом руками в программе поставил вычисленное.  
Нужно было здесь воспользоваться тем, что ты вычислил:
```python
num_1 = result_1[ind_num_1:22]
```

2023-12-11 09:50 UTC, eugene-okulik commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +result = '"результат операции: 42", "результат операции : 514", "результат работы программы: 9"'
Не, какая-та эта наша вымышленная программа отвечает один раз за запуск, она не выдает сплошным текстом все результаты, а выдает их по одному. Т.е. первый вариант выполнения ближе к задуманному.

2023-12-11 11:02 UTC, cryptomup commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +ind_num_1 = result_1.index("42")
ок, вечером найду индексы после двоеточия
первое и третье задание - ок?

2023-12-11 11:04 UTC, cryptomup commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +result = '"результат операции: 42", "результат операции : 514", "результат работы программы: 9"'
ок, попробую с list

2023-12-12 07:29 UTC, eugene-okulik approved these changes

2023-12-12 07:29 UTC, eugene-okulik commented on homework/maksim_stulau/homework_5/file_hw_2.py
> +ind_num_3 = result_3.index(':') + 2
:+1:

2023-12-12 07:29 UTC, merged